# Generated by Django 4.1 on 2022-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="gst_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
