# Generated by Django 4.1 on 2022-10-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_alter_seller_gst_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pic",
            field=models.FileField(default="sad.jpg", upload_to="products"),
        ),
    ]
